version: "3"

services:
  mysql:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: flash_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      timeout: 30s
      retries: 10

  app:
      build: .
      ports:
        - "3000:80"
      environment:
        DATABASE_URL: "mysql://root:secret@mysql/flash_db"
      depends_on:
        mysql:
          condition: service_healthy